Add zilla dump command
aklivity/zilla-docs pull request #157
Opened 2023-12-19 20:16 UTC by attilakreiner

2023-12-19 20:43 UTC, vordimous commented
@attilakreiner can you update the page ToC with the below so github still lets me approve this pr:

```
- [zilla dump](#zilla-dump)
  - [-a --affinity `<affinity>`](#a-affinity-affinity)
  - [-b --bindings `<bindings>`](#b-bindings-bindings)
  - [-i --install `<plugin-directory>`](#i-install-plugin-directory)
  - [-v --verbose](#v-verbose)
  - [-w --write](#w-write)
- [zilla generate](#zilla-generate)
  - [-t --template `<template>`](#t-template-template)
  - [-i --input `<input-file>`](#i-input-input-file)
  - [-o --output `<output-file>`](#o-output-output-file)
- [zilla help](#zilla-help)
- [zilla metrics](#zilla-metrics)
  - [--namespace `<namespace>`](#namespace-namespace)
- [zilla start](#zilla-start)
  - [-v --verbose](#v-verbose-1)
  - [--workers](#workers)
- [zilla stop](#zilla-stop)
- [zilla tune](#zilla-tune)
```

2023-12-19 20:50 UTC, vordimous commented on src/reference/config/zilla-cli.md
> +To find the Wireshark plugin directory check here: About Wireshark -> Folders -> Personal Lua Plugins; or use this command: `tshark -G folders | grep "Personal Lua Plugins"`.
````suggestion
To find the Wireshark plugin directory navigate the menu: About Wireshark -> Folders -> Personal Lua Plugins; or use this command:

```bash:no-line-numbers
tshark -G folders | grep "Personal Lua Plugins"
```

````

2023-12-19 20:52 UTC, vordimous requested changes

2023-12-19 20:52 UTC, vordimous commented on src/reference/config/zilla-cli.md
> +To find out the plugin version check here: About Wireshark -> Plugins -> search: zilla; or use this command: `tshark -G plugins | grep zilla`.
````suggestion
To find out the plugin version navigate the menu: About Wireshark -> Plugins -> search: zilla; or use this command:

```bash:no-line-numbers
tshark -G plugins | grep zilla
```

````
```

2023-12-19 21:19 UTC, vordimous approved these changes

2023-12-20 17:24 UTC, jfallows approved these changes

2023-12-20 19:52 UTC, merged