Catalog reference
aklivity/zilla-docs pull request #162
Opened 2024-01-02 06:38 UTC by aDaemonThread

2024-01-02 06:42 UTC, jfallows approved these changes

2024-01-02 15:01 UTC, vordimous requested changes

2024-01-05 12:44 UTC, aDaemonThread commented on src/reference/config/catalogs/catalog-schema-registry.md
> +Schema Registry URL
No, afaik. We hit the Schema registry endpoint using REST APIs and those request & response structure is consistent over versions.

2024-01-05 13:55 UTC, vordimous requested changes
looks good, just two small quick things. the required indicator `*` goes on the title of the property and inside the link text of the table of contents. Then just double check they match each other.

So if inline `options.subjects` are required then the header is `#### options.subjects\*` and the ToC is `- [options.subjects\*](#options-subjects)`

2024-01-05 14:45 UTC, vordimous approved these changes

2024-01-05 14:46 UTC, merged