Simplify kafka client bootstrap server names and ports config updates
aklivity/zilla-docs pull request #167
Opened 2024-01-09 00:50 UTC by akrambek

2024-01-09 04:20 UTC, jfallows requested changes

2024-01-09 04:20 UTC, jfallows commented on src/reference/config/bindings/binding-tls.md
> +> `boolean` Default value is `true`
...when `trust` is `null`

2024-01-09 05:26 UTC, jfallows submitted a review, later dismissed

2024-01-09 05:53 UTC, jfallows approved these changes

2024-01-09 13:30 UTC, vordimous commented on src/reference/config/bindings/binding-tls.md
> +> `boolean` Default value is `true` when trust is `null`
```suggestion
> `boolean` | Default: `true` when trust is `null`
```
A small change to align with the other `Default` definitions

2024-01-09 13:32 UTC, vordimous commented on src/reference/config/bindings/binding-tcp.md
> -    port: 12345
These don't need to be removed from the global sample unless they are being removed from the spec. For each binding, we want a description and Full example code block. We will update the examples to use the new feature but reference docs can describe everything.

2024-01-09 13:35 UTC, vordimous commented on src/reference/config/bindings/binding-kafka.md
> +- [options.servers](#options-servers)
Can you update the order of the ToC or the property section so they are in the same order. 
`### options.servers` is before `### options.sasl`, for instance.

2024-01-10 20:02 UTC, vordimous approved these changes

2024-01-18 17:28 UTC, merged