Model & View update
aklivity/zilla-docs pull request #181
Opened 2024-01-31 04:28 UTC by aDaemonThread

2024-01-31 13:42 UTC, vordimous commented on src/reference/config/models/model-core.md
> +model: string
are there more options than just `string`?

2024-01-31 13:44 UTC, vordimous commented on src/reference/config/models/model-avro.md
> +### catalog\*
and add this to the other files where it is necessary.

2024-01-31 17:20 UTC, vordimous requested changes

2024-01-31 17:20 UTC, vordimous commented on src/reference/config/models/model-protobuf.md
> +Transforms the model from this data type to the Avro schema on produce and to this data type from the Avro schema on consume.
```suggestion
Transforms the model from this data type to the Protobuf schema on produce and to this data type from the Protobuf schema on consume.
```

2024-01-31 18:16 UTC, vordimous submitted a review, later dismissed

2024-02-01 03:50 UTC, jfallows submitted a review, later dismissed

2024-02-01 04:59 UTC, jfallows approved these changes

2024-02-01 13:20 UTC, merged