AWS CloudWatch Exporter docs update
aklivity/zilla-docs pull request #194
Opened 2024-02-27 16:56 UTC by aDaemonThread

2024-02-28 16:11 UTC, vordimous submitted a review, later dismissed

2024-02-28 19:29 UTC, jfallows requested changes

2024-02-28 19:29 UTC, jfallows commented on src/reference/config/telemetry/exporters/exporter-aws.md
> +        namespace: zilla
```suggestion
        namespace: zilla-metrics
```

2024-02-28 19:29 UTC, jfallows commented on src/reference/config/telemetry/exporters/exporter-aws.md
> +    namespace: zilla
```suggestion
    namespace: zilla-metrics
```

2024-02-29 15:16 UTC, jfallows approved these changes

2024-05-30 22:21 UTC, jfallows reviewed
@aDaemonThread please rename `aws` exporter to `aws-cloudwatch` exporter.

2024-05-30 22:21 UTC, jfallows reviewed
@vordimous please hold off on merging until this has been renamed.

2024-05-31 13:50 UTC, jfallows requested changes

2024-05-31 13:50 UTC, jfallows commented on src/reference/config/telemetry/exporters/exporter-aws.md
Please rename file to `exporter-aws-cloudwatch.md`.

2024-05-31 14:47 UTC, vordimous requested changes

2024-06-01 16:59 UTC, jfallows approved these changes

2024-06-04 00:13 UTC, merged