fix: rename karapace catalog
aklivity/zilla-docs pull request #226
Opened 2024-05-10 19:07 UTC by vordimous

2024-05-10 21:00 UTC, jfallows requested changes

2024-05-10 21:00 UTC, jfallows commented on src/reference/config/catalogs/catalog-karapace.md
>  :::
Please review all features marked incubator as many features moved out of incubator during the last release.

2024-05-10 21:00 UTC, jfallows commented on src/reference/config/catalogs/catalog-karapace.md
> -description: Zilla runtime schema-registry catalog
Note: `schema-registry` catalog remains, just in `zilla-plus` now, so `karapace` catalog is net new.

2024-05-11 04:12 UTC, aDaemonThread requested changes

2024-05-11 04:12 UTC, aDaemonThread commented on src/reference/config/catalogs/catalog-karapace.md
> +Schema Registry URL to access schemas via API calls.
Replace Schema Registry with Karapace Registry

2024-05-30 14:27 UTC, vordimous commented
@jfallows I think we need to merge this PR until https://github.com/aklivity/zilla-plus/issues/273 is completed and we can make the necessary adjustments in the docs.

2024-06-04 00:11 UTC, jfallows approved these changes

2024-06-04 00:12 UTC, merged